<?php

namespace Database\Seeders\Helpers;

use Illuminate\Support\Facades\Storage;

class ImageGenerator
{
    private static array $colors = [
        [41, 128, 185],   // Blue
        [39, 174, 96],    // Green  
        [192, 57, 43],    // Red
        [142, 68, 173],   // Purple
        [243, 156, 18],   // Orange
        [22, 160, 133],   // Teal
        [231, 76, 60],    // Coral
        [44, 62, 80],     // Dark Blue
        [211, 84, 0],     // Dark Orange
        [41, 105, 176],   // Royal Blue
    ];

    public static function generateProductThumbnail(string $productName, int $index = 0): string
    {
        $width = 400;
        $height = 400;
        $img = imagecreatetruecolor($width, $height);

        // Background color
        $colorSet = self::$colors[$index % count(self::$colors)];
        $bg = imagecolorallocate($img, $colorSet[0], $colorSet[1], $colorSet[2]);
        imagefill($img, 0, 0, $bg);

        // Lighter overlay rectangle
        $lighter = imagecolorallocatealpha($img, 255, 255, 255, 100);
        imagefilledrectangle($img, 20, 20, $width - 20, $height - 20, $lighter);

        // Text
        $white = imagecolorallocate($img, 255, 255, 255);
        $fontSize = 4; // Built-in font size (1-5)

        // Center the product name
        $lines = wordwrap($productName, 15, "\n", true);
        $lineArray = explode("\n", $lines);
        $lineHeight = imagefontheight($fontSize) + 4;
        $totalHeight = count($lineArray) * $lineHeight;
        $startY = ($height - $totalHeight) / 2;

        foreach ($lineArray as $i => $line) {
            $textWidth = imagefontwidth($fontSize) * strlen($line);
            $x = ($width - $textWidth) / 2;
            $y = $startY + ($i * $lineHeight);
            imagestring($img, $fontSize, (int) $x, (int) $y, $line, $white);
        }

        // Add "PRODUCT" label at top
        $labelText = 'PRODUCT IMAGE';
        $labelWidth = imagefontwidth(2) * strlen($labelText);
        $labelColor = imagecolorallocatealpha($img, 255, 255, 255, 60);
        imagestring($img, 2, ($width - $labelWidth) / 2, 30, $labelText, $labelColor);

        // Save
        $filename = 'product_' . str_replace(' ', '_', strtolower($productName)) . '_' . $index . '.png';
        $relativePath = 'productImages/' . $filename;
        $absolutePath = storage_path('app/public/' . $relativePath);

        // Ensure directory exists
        $dir = dirname($absolutePath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        imagepng($img, $absolutePath);
        imagedestroy($img);

        return $relativePath;
    }

    public static function generatePaymentProof(int $invoiceId, int $index = 0): string
    {
        $width = 600;
        $height = 400;
        $img = imagecreatetruecolor($width, $height);

        // White background
        $white = imagecolorallocate($img, 245, 245, 245);
        imagefill($img, 0, 0, $white);

        // Header bar
        $headerColor = imagecolorallocate($img, 41, 128, 185);
        imagefilledrectangle($img, 0, 0, $width, 60, $headerColor);

        // Header text
        $textWhite = imagecolorallocate($img, 255, 255, 255);
        imagestring($img, 5, 20, 20, 'BUKTI TRANSFER', $textWhite);

        // Invoice info
        $black = imagecolorallocate($img, 33, 33, 33);
        $gray = imagecolorallocate($img, 120, 120, 120);

        imagestring($img, 4, 20, 80, 'Invoice #' . $invoiceId, $black);
        imagestring($img, 3, 20, 110, 'Tanggal: ' . now()->format('d/m/Y H:i'), $gray);
        imagestring($img, 3, 20, 135, 'Status: BERHASIL', $gray);
        imagestring($img, 3, 20, 160, 'Bank: BCA / Mandiri / BNI', $gray);

        // Decorative line
        $lineColor = imagecolorallocate($img, 200, 200, 200);
        imageline($img, 20, 190, $width - 20, 190, $lineColor);

        // Stamp-like text
        $stampColor = imagecolorallocatealpha($img, 39, 174, 96, 40);
        imagestring($img, 5, 200, 250, 'LUNAS', $stampColor);

        // Footer
        imagestring($img, 2, 20, $height - 30, 'Placeholder - Generated by Seeder', $gray);

        $filename = 'proof_invoice_' . $invoiceId . '_' . $index . '.png';
        $relativePath = 'paymentProofs/' . $filename;
        $absolutePath = storage_path('app/public/' . $relativePath);

        $dir = dirname($absolutePath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        imagepng($img, $absolutePath);
        imagedestroy($img);

        return $relativePath;
    }
}
